[package]
name = "resumemk_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.22", features = ["derive"] }
headless_chrome = "1.0.15"
resume_builder = {path = "../resume_builder"}

[[bin]]
name = "resumemk_cli"
path = "src/main.rs"
